name: Build
on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install pygame pyinstaller pillow
      - run: pyinstaller --windowed --name 2048 --icon icon.png main.py
      - uses: actions/upload-artifact@v4
        with:
          name: 2048-${{ matrix.os }}
          path: dist/